### ISSUE TITLE
how to render page data ?

### ISSUE THREAD

**Issue by kousar2334** [HansSchouten/Laravel-Pagebuilder#22] opened 2020-06-28 05:43 UTC
public function viewPage($pageId)
   {
    $data=DB::table('pagebuilder__pages')->where('id',$pageId)->value('data');
   	return $data;
   }
I get the page data from the function, How can I render the data into blade?

**Comment by HansSchouten** [comment] 2020-06-28 06:06
When the `$data` is rendered it is a full html structure, so I suggest not to pass it to a blade view file since it is already a full webpage. There are multiple ways to render the data from one page, you could do this:

```
use PHPageBuilder\Theme;
use PHPageBuilder\Modules\GrapesJS\PageRenderer;

$page = (new PageRepository)->findWithId($pageId);
$theme = new Theme(config('pagebuilder.theme'), config('pagebuilder.theme.active_theme'));
$pageRenderer = new PageRenderer($theme, $page);
$html = $pageRenderer->render();
```

**Comment by kousar2334** [comment] 2020-06-28 06:20
I have copied the function but there is an error. 
Error
Call to a member function findWithId() on null
http://127.0.0.1:8000/admin/pages/1

**Comment by HansSchouten** [comment] 2020-06-28 06:36
On what line of the code this this error occur? Can you further debug the cause, this error does not reveal to me what causes it.

**Comment by kousar2334** [comment] 2020-06-28 06:42
public function findWithId($id)

    {

        return $this->createInstance($this->db->findWithId($this->table, $id));//the error is occur this line

    }
![Screenshot_2020-06-28_12-40-03](https://user-images.githubusercontent.com/23190775/85940200-d02ce180-b93c-11ea-9b55-7d6c8482c108.png)

**Comment by HansSchouten** [comment] 2020-06-28 06:51
Ok that shows me what is the issue, the DB is not instantiated. This makes sense because this is done when we create a PHPageBuilder instance, which we did not do. I just committed a fix to the master which will be part of the next release.
For now you can add this to the boot method of your ServiceProvider:

```
$this->app->singleton('phpPageBuilder', function($app) {
    return new PHPageBuilder(config('pagebuilder'));
});
$this->app->make('phpPageBuilder');
```

**Comment by kousar2334** [comment] 2020-06-28 07:09
![Screenshot_2020-06-28_13-08-46](https://user-images.githubusercontent.com/23190775/85940804-880fbe00-b940-11ea-8041-cf27ced60929.png)
there is an error.

**Comment by HansSchouten** [comment] 2020-06-28 07:15
Yes everytime you create an instance of a class that is not inside the current folder, you need to include it with `use [namespace]`. If you switch to an editor like PhpStorm it warns you of this and helps to fix it. In this case you need to add `use PHPageBuilder\PHPageBuilder;`.

**Comment by kousar2334** [comment] 2020-06-28 07:22
it works. thank you so much.

**Closed** 2020-06-28 07:22 UTC

**Comment by mansmahamat** [comment] 2020-07-07 09:07
> public function viewPage($pageId)
> {
> $data=DB::table('pagebuilder__pages')->where('id',$pageId)->value('data');
> return $data;
> }
> I get the page data from the function, How can I render the data into blade?





> When the `$data` is rendered it is a full html structure, so I suggest not to pass it to a blade view file since it is already a full webpage. There are multiple ways to render the data from one page, you could do this:
> 
> ```
> use PHPageBuilder\Theme;
> use PHPageBuilder\Modules\GrapesJS\PageRenderer;
> use PHPageBuilder\Repositories\PageRepository;
> 
> public function viewPage($pageId)
> {
> 	$theme = new Theme(config('pagebuilder.theme'), config('pagebuilder.theme.active_theme'));
> 	$page = (new PageRepository)->findWithId($pageId);
> 	$pageRenderer = new PageRenderer($theme, $page);
> 	$html = $pageRenderer->render();
> 	return $html;
> }
> ```

Where write this code ?

**Comment by HansSchouten** [comment] 2020-07-07 14:39
You can make a Laravel controller action with this snippet.
